spring:
  application:
    name: ecommerce-challenge
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: 53cR3T@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
